<a href="https://colab.research.google.com/github/nesrinetrimech/Fall-Detection-Model/blob/main/Fall_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
from sklearn import linear_model, preprocessing
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("data.csv")

In [ ]:
print (data)

      Accelerometer  Decision 
0               1.0          1
1               1.0          2
2               0.0          0
3               1.0          1
4               0.0          0
...             ...        ...
2034            1.0          2
2035            1.0          2
2036            1.0          1
2037            1.0          2
2038            0.0          0

[2039 rows x 2 columns]


In [ ]:
data.columns

Index(['Accelerometer', 'Decision '], dtype='object')

In [ ]:
Accelerometer = list(data["Accelerometer"])

In [ ]:
Decision = list(data["Decision "])

In [ ]:
predict = "class"

In [ ]:
X = list(zip(Accelerometer))
Y = list(Decision)


In [ ]:
x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X,Y, test_size=0.1)

In [ ]:
model = KNeighborsClassifier(n_neighbors=3)

In [ ]:
model.fit(x_train, y_train)
acc = model.score(x_test, y_test)
print(acc)

0.6470588235294118


In [ ]:
error = 1 - model.score(x_test, y_test)
print('Erreur: %f' % error)

Erreur: 0.352941


In [ ]:
#look closely about wheather each train and test is correct
predicted = model.predict(x_test)
naems = ["unacc", "acc", "good", "very good"]
for x in range(len(predicted)):
    print("Predicted: ", predicted[x], "data: ", x_test[x], "Actual:", y_test[x] )
    n=model.kneighbors([x_test[x]], 1, True)
    print(n)

Predicted:  0 data:  (0.0,) Actual: 0
(array([[0.]]), array([[59]]))
Predicted:  2 data:  (1.0,) Actual: 2
(array([[0.]]), array([[3]]))
Predicted:  2 data:  (1.0,) Actual: 2
(array([[0.]]), array([[3]]))
Predicted:  2 data:  (1.0,) Actual: 1
(array([[0.]]), array([[3]]))
Predicted:  0 data:  (0.0,) Actual: 0
(array([[0.]]), array([[59]]))
Predicted:  2 data:  (1.0,) Actual: 2
(array([[0.]]), array([[3]]))
Predicted:  2 data:  (1.0,) Actual: 2
(array([[0.]]), array([[3]]))
Predicted:  0 data:  (0.0,) Actual: 0
(array([[0.]]), array([[59]]))
Predicted:  2 data:  (1.0,) Actual: 1
(array([[0.]]), array([[3]]))
Predicted:  2 data:  (1.0,) Actual: 2
(array([[0.]]), array([[3]]))
Predicted:  2 data:  (1.0,) Actual: 1
(array([[0.]]), array([[3]]))
Predicted:  0 data:  (0.0,) Actual: 0
(array([[0.]]), array([[59]]))
Predicted:  2 data:  (1.0,) Actual: 1
(array([[0.]]), array([[3]]))
Predicted:  2 data:  (1.0,) Actual: 2
(array([[0.]]), array([[3]]))
Predicted:  2 data:  (1.0,) Actual: 1
(array

In [ ]:
#predict from the give data and print out result
print(model.predict([[0]]))

[0]
